version: '2'
services:
  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: midsk
      MYSQL_DATABASE: dataProject
    ports:
      - "3307:3306"
    expose:
      - 3306
  web:
    build: .
    container_name: web_container
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db
    expose:
      - 8080
